### ISSUE TITLE
Extract www and/or showcase from this project

### ISSUE THREAD

**Issue by thegaryroberts** [denoland/fresh#1020]
It would be helpful if the docs website (but at a minimum the showcase additions) could be moved out from this main project. The commit noise makes it very time consuming working out what meaningful framework changes are contained within each release.

**Comment by OldManFroggy** [comment]
I also would like to see this,  the release notes are overloaded with showcase examples (of greatly varying quality)

In my opinion, there are far too many showcases right now of low quality, for example, I was working with one of my Corp. clients they looked at fresh and after looking at the showcases, decided that:

1. low-quality examples, can't be any good if this is the showcase of how good fresh is...
2. there are soo many showcase items, a fair few by the same author look desperate to get new users...

In the end, they wanted to go with SvelteKit.

Either way, the showcases should be curated now that there are soo many.  At least put the best showcase examples of Fresh at the top of the list...

**Comment by hashrock** [comment]
We have discussed this issue with the team, and for now we would like to keep `www/` in the repository, as it will be used to verify the functionality of the latest fresh. It is also seems undesirable to have only showcase in a separate repository, since its assets would be served from a different domain. I'd like to put it on the agenda again after 2.0.

For now, I have created a `showcase` section in the 1.1.4 release notes.

The showcase has been sorted and organized only once. I have moved up the order of projects that I found interesting or that is opensourced. Whatever, I think it needs to be done on an ongoing basis.

**Comment by marvinhagemeister** [comment]
It's unlikely that we'll move out the `www`-folder into a repository anytime soon. It's neat to have it here because it allows us to test new fresh features easily. Our new structure in the release notes separates changes to `www` from the rest, which to me addresses the original posts concern about it being hard to decipher what changed in a release.

**Comment by thegaryroberts** [comment]
@marvinhagemeister the separation of release notes into sections does resolve my issue. Even better if we can get a blog post with each release! Anyway thanks for this.

P.S delighted to see maintenance of this excellent project spinning up again!

**Comment by marvinhagemeister** [comment]
@thegaryroberts We got a blog post with the latest fresh 1.2 release: https://deno.com/blog/fresh-1.2 Plan is to have one for every future release too. The blog post is linked in the GitHub release page as well.
