### ISSUE TITLE
How to load data from db into signals

### ISSUE THREAD

**Issue by xb1g** [denoland/fresh#1119]
how to load data from database to signals and use the signals in islands.

I create a function to load the data from mongo in `utils/cart` file and run it after the signal was created but it does't work (breaks every signals and island interactivity?)

```ts

  const cartData = await db.collection<{ _id: string; text: string }>("texts")
    .find().toArray();

  console.log(cartData.map((c) => c.text), "carts");

  cart.value = cartData.map((c) => c.text);
```
i ran it in main.ts before start, same results

i move the function out of `utils/cart` to elsewhere, then ran it in main.ts => it flashes the data, but doesn't breaks islands and signals

it seems that i cannot use mongo functions in the same file as signals

also if i get data from fetch, it flashes then it's gone. so the problem isn't from mongo, but how to load the initial data into signals when the page loads.

**Comment by innovatedev-john-pope** [comment]
Signals are also run on the client, not just the server. You can't do any server-side operations with them directly, or when they are run on the client they won't have access to server only data/methods and will cause errors, just like islands, because they have to be included from an island. The signals can be placed in any folder (outside of routes and islands as that would cause issues for the fresh.gen.ts). When you import it in an island it gets included in the bundle no matter where you created it at.

You could wrap the server specific code with a `!IS_BROWSER` check - just keep in mind any files you import are bundled with the js sent to the client, so make sure you aren't leaking anything you wouldn't want on the client and it isn't going to have access to stuff that is related to the request if you do it that way (like the user/session).

One other option I have used is to create an island that receives the data through its props, import the signal in that island, then update the signal value there in a useEffect.

Here is the counter island updated to use signals like this:

```ts
import { score } from "../data/signals.ts";

//...
import { useEffect } from "preact/hooks";
import { Button } from "../components/Button.tsx";
import { score } from "../data/signals.ts";

interface CounterProps {
  start?: number;
}

export default function Counter(props: CounterProps) {
  useEffect(() => {
    if(props.start === undefined) return;

    score.value = props.start!;
  }, [props.start]);

  return (
    <div class="flex gap-2 w-full">
      <p class="flex-grow-1 font-bold text-xl">{score.value}</p>
      <Button onClick={() => score.value -= 1}>-1</Button>
      <Button onClick={() => score.value += 1}>+1</Button>
    </div>
  );
}
```

Other islands can just import the signal and use as expected now, but you may need/want to wrap parts with checks to see if the signal has been populated yet depending on what you are doing. I find that if I make an island that the only thing it does is initialize any signals that needed data from the server it seems to simplify things.

To use request-based information, such as URL or session data, initializing the signal with a useEffect is the best way I've found to get data into signals.

**Comment by xb1g** [comment]
i ended up getting the data from handler, pass it to the island, and put it in `useSignal` which I think is how it should be done in this architecture?

**Comment by lucacasonato** [comment]
You can now pass `Signal<T>` directly in island props (they now get serialized from server to client).

Should be releasing in Fresh 1.2 next week.
