### ISSUE TITLE
Task not found: screenshot

### ISSUE THREAD

**Issue by gedw99** [denoland/fresh#1156]
also here but closed: https://github.com/denoland/fresh/issues/1056

but still not working

```

# install
curl -fsSL https://deno.land/x/install/install.sh | sh

# start demo
deno task start
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
Listening on http://localhost:8000/

# take a screenshot
deno task screenshot http://localhost:8000/ deno-fresh-demo
Task not found: screenshot
Available tasks:
- start
    deno run -A --watch=static/,routes/ dev.ts
```

**Comment by ryuapp** [comment]
Hello @gedw99 .

Did you clone [fresh](https://github.com/denoland/fresh)? `deno task screenshot` available in fresh.
`Task not found: screenshot` means it's not written in `deno.json`.
But the task command is written in [here](https://github.com/denoland/fresh/blob/2d124aacf4ab33d3e74edda734a9b0cf732157f2/deno.json)

Please try to clone [fresh](https://github.com/denoland/fresh) and try `deno task screenshot` again.

**Comment by kjloveless** [comment]
I think @gedw99 means that a Fresh project scaffolded with 

`deno run -A -r https://fresh.deno.dev deno-fresh-demo`

isn't actually a clone of the github repo. 
The README is misleading because following it would make you believe that the screenshot task is included in the scaffold. 
However, if you look closer at the init.ts unit you'll see that the deno.json being created only looks like this:

```
const config = {
  tasks: {
    start: "deno run -A --watch=static/,routes/ dev.ts",
  },
  importMap: "./import_map.json",
  compilerOptions: {
    jsx: "react-jsx",
    jsxImportSource: "preact",
  },
};
```

I don't necessarily think that the screenshot task should be included in every scaffold, but maybe creating another script to add the functionality and updating the README to include that step would make sense,

ex:
`deno run -A -r https://fresh.deno.dev/add_screenshot .`

**Comment by gedw99** [comment]
@kjloveless urs that is what I mean …

**Comment by gedw99** [comment]
Yes just updating the readme to show how to activate the s teen shot would help

**Comment by ryuapp** [comment]
Oh sry, I misunderstood.
