### ISSUE TITLE
proposal(docs): add example on how to use twindv1

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#1220]
See #946

**Comment by tunnckoCore** [comment]
@iuioiua good point. ~~I struggle to get it working..~~

Fixed it. From the basic template, i just switched to use the official twindv1 plugin in the `main.ts`, and the `@twind/core@1.1.3` on the `twind.config.ts`.

https://github.com/tunnckoCore/deno-fresh-tailwindV3-template

I also like import maps to be inside the `deno.json` so that's the two changes from the bare template.

**Comment by lino-levan** [comment]
#1271 landed, I believe this should be closed.

**Comment by iuioiua** [comment]
Completed in #1271.
