### ISSUE TITLE
Add docs on how to enable CORS for a route

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#1247]
IE how to handle OPTION requests in a route, or maybe using a middleware.

**Comment by adamgasiorek** [comment]
Yeah, please provide some docs. It is ultra important. Any progress about it? @lucacasonato

**Comment by deer** [comment]
I'm working on this. If you are desperate, this should get you sorted:
https://github.com/denoland/fresh/blob/76d838cf105621a2bd86d3b04259d7bcc1e37941/tests/fixture/routes/_middleware.ts#L4

**Comment by deer** [comment]
Additionally, until I create the PR for the documentation, there are the following examples:
* https://github.com/deer/fresh_cors_example_client
* https://github.com/deer/fresh_cors_example_server
* live test: https://fresh-cors-example-client.deno.dev/

I am happy to receive PRs, since these can probably be improved.
