### ISSUE TITLE
_500.tsx not rendering if error is thrown inside GET handler

### ISSUE THREAD

**Issue by J053Fabi0** [denoland/fresh#1357]
Having set `routes/_500.tsx` like this:

```ts
import { ErrorPageProps } from "$fresh/server.ts";

export default function Error500Page({ error }: ErrorPageProps) {
  return <p>500 internal error: {(error as Error).message}</p>;
}
```

It's not rendering when the error is thrown inside the GET handler.

```ts
import { Handlers } from "$fresh/server.ts";

export const handler: Handlers<undefined, undefined> = {
  GET(req, ctx) {
    if ([].length === 0) throw new Error("This is a test error");

    return ctx.render();
  },
};

export default function Home() {
  return <p>All right</p>;
}
```

![image](https://github.com/denoland/fresh/assets/12930717/05b141d9-853f-4dea-b621-6e3405ee4cbe)

Only when it's thrown inside the component itself.

```ts
export default function Home() {
  if ([].length === 0) {
    throw new Error("This is a test error");
  }
  return <p>All right</p>;
}
```
![image](https://github.com/denoland/fresh/assets/12930717/d6e25663-9f04-4dc0-88a9-ea987b85e119)

I'm using fresh `1.2.0`.

**Comment by deer** [comment]
Thanks for the good... issue. I struggle to call this a bug, since it nicely straddles the line between bug and feature. You can initialize your server with a different error handler, if you're unsatisfied with the current message. See the [docs](https://deno.land/std@0.192.0/http/server.ts?s=ServeInit#prop_onError) here. In particular it says: `The handler to invoke when route handlers throw an error.`

Here's a short example of a modified `main.ts`:
```ts
await start(manifest, {
  plugins: [twindPlugin(twindConfig)],
  onError: (error: unknown) => {
    console.error(error);
    return new Response("look a different error", { status: 500 });
  },
});
```

This doesn't at all seem like the desired behavior, and Fresh should certainly do for the user, even if it's just a boolean, something like "use _500 page for route handler errors". I guess I'm surprised this hasn't been brought up before. I'll keep looking for a bit, to see if I can implement this.

**Comment by marvinhagemeister** [comment]
+1 for always using the `_500.tsx` template if available. I think we should even generalize this behavior for all error response status codes.

**Comment by deer** [comment]
I did manage to hack something together in order to get this working. Then I tried to write a test. Sadly I wasn't able to reproduce the error, even after reverting my hacky fix.

Turns out the problem goes away if you introduce a `_middleware.ts` like this:
```ts
import { MiddlewareHandlerContext } from "$fresh/server.ts";

export async function handler(
  _req: Request,
  ctx: MiddlewareHandlerContext,
) {
  return await ctx.next();
}
```
(And all the tests in `main_test.ts` are subject to some middleware.) Of course any middleware which is more complicated than this will work as well.

I started looking into this a bit more, but didn't make a whole lot of progress. I'll try later this week. If anyone has any great insight into why `return middlewareCtx.next().catch((e) => errorHandler(req, ctx, e));` doesn't seem to catch when there is no middleware, that would be great.
