### ISSUE TITLE
Type Safety: Passing server data to components

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1386]
From a twitter thread:

> **CodeMonument:** Also, a question regarding request handlers and passing data to the component: 
> Can we somehow infer typing for these component props automatically? 
> So that I can add some data to the rendering in the handler function and have the props in the component autocomplete?
> That's basically the case I'd try to circumvent with async components, as the data would simply be in scope of the async components and therefore correctly typed.

**Comment by marvinhagemeister** [comment]
Todos:
- Look into async server components.
- Look into Remix + SvelteKit loaders
- Look how nuxt or nextjs do it
- Come up with our own approach?

**Comment by bjesuiter** [comment]
Hi, CodeMonument here! (CodeMonument being my development persona, my personal accounts are bjesuiter ;) ) 

I'd like to add some context to this request/idea. 
I'm a huge fan of [Theo Browne - t3dotgg](https://github.com/t3dotgg) and he's currently doing a lot of educational work about NextJS 13 with the new App Router (also called "App Directory"), which is heavily based on React Server Components (RSCs). 
Now, I'm not sure yet what to think about NextJS, since I'm not a react fan at all, but I like the editing experience of these RSCs quite a bit, especially the async variant. 

## Fresh Handler vs. async RSC 

Given the following component (from my repo: [Deno Audio Logbook](https://github.com/codemonument/deno_audio_logbook/blob/main/routes/userarea/calendar/%5Byear%5D/%5Bmonth%5D.tsx)): 

```ts
type HomeProps = PageProps<
  {
    user: UserSession;
    date: LogbookDate;
    monthAudios: Audio[];
    theme: Theme;
  }
>;

export default function Home({ data }: HomeProps) {
  return (
    <Layout user={data.user} theme={data.theme}>
      <LoadSidebar />
      <Control date={data.date} audios={data.monthAudios} />
    </Layout>
  );
}
```

As you see, I need to declare the types of the props given to this component.  

Now I'll add my route handler for data fetching: 

```ts
/**
 * @requires ctx.state.user => The user session, resolved by the _middleware.ts file
 */
export const handler: Handlers<unknown, UserareaContext> = {
  async GET(_req, ctx) {
    // Parse correct year and month params from url
    const { year, month } = ctx.params;
    const parsedDate = LogbookDate.safeParse({ month, year });
    const user = ctx.state.user;

    // Redirect to date error page when parsing failed
    if (!parsedDate.success) {
      return gotoInternal("/userarea/errors/date-parsing");
    }

    // DB Queries
    const monthAudiosMeta = await getAudioMetadataForMonth(
      user.userId,
      parsedDate.data,
    );

    const monthAudiosPromises = monthAudiosMeta.map(async (audioMeta) => {
      const presignedUrl = await s3.getPresignedUrl("GET", audioMeta.filePath);
      return {
        ...audioMeta,
        url: presignedUrl,
      };
    });

    const monthAudios = await Promise.all(monthAudiosPromises);

    // Render calendar with audio and user objects
    return ctx.render({
      user,
      date: parsedDate.data,
      monthAudios,
      theme: ctx.state.theme,
    });
  },
};
```

Besides the fact, that ctx.state is also untyped by default / has to be typed by myself 
(which is it's own discussion - see https://github.com/denoland/fresh/issues/1387), 
you can see that the shape of the props data is pretty clear from the call to the ctx.render function. 

In RSC land, this szenario would look more like this: 

```ts

export default async function Home(req, ctx) {

 // Parse correct year and month params from url
    const { year, month } = ctx.params;
    const parsedDate = LogbookDate.safeParse({ month, year });
    const user = ctx.state.user;

    // Redirect to date error page when parsing failed
    if (!parsedDate.success) {
      return gotoInternal("/userarea/errors/date-parsing");
    }

    // DB Queries
    const monthAudiosMeta = await getAudioMetadataForMonth(
      user.userId,
      parsedDate.data,
    );

    const monthAudiosPromises = monthAudiosMeta.map(async (audioMeta) => {
      const presignedUrl = await s3.getPresignedUrl("GET", audioMeta.filePath);
      return {
        ...audioMeta,
        url: presignedUrl,
      };
    });

    const monthAudios = await Promise.all(monthAudiosPromises);
    


    //  This is the previous "render" call
    // return ctx.render({
    //  user,
    //  date: parsedDate.data,
    //  monthAudios,
    //   theme: ctx.state.theme,
   //  });

    // To keep the template the same, I'll alias these variables here, but this is not necessary
    const date = parsedDate.data;
    const theme = ctx.state.theme;

  return (
    <Layout user={user} theme={theme}>
      <LoadSidebar />
      <Control date={date} audios={monthAudios} />
    </Layout>
  );
}

```

## Benefits 

- indirection by using a props-object is not necessary anymore, since all variables for template rendering are in scope already 
- manual typing of the props-object is not necessary anymore, since the whole props object got superfluous. 
- it should be possible to do parallel data fetching in here, 
  at least nextJs is doing it: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#parallel-data-fetching

## Disclaimer 

I've not looked into the details of this, but I like the simplicity when combining the handler with the Component. 
(At least for GET Requests)

## Additions 

This might get event better with correct Suspense and Error Components and Streaming
https://nextjs.org/docs/app/building-your-application/data-fetching#streaming-and-suspense

**Comment by marvinhagemeister** [comment]
@bjesuiter Thank you so much for writing down your thoughts on this one. I really like the proposal and I agree that it could make things simpler. Heck, it even seems natural to allow handlers to return JSX directly instead of them being responsible of kicking of rendering themselves.

A downside of this approach is that custom error handling or similar things may get more dificult:

```jsx
// Measuring render or doing error handling can be done
// via try/catch today.
function handler(req, ctx) {
  const start = Date.now();
  try {
     await ctx.render()
   } finally {
     console.log("Rendering took " + (Date.now() - start) + "ms");
   }
}
```

But then again, maybe that's something that should be moved to a middleware instead. It seems less like the common scenario, but more a niche usage. Even if that's required I think we could find a solution for that. What I like about your proposal is that it plays well with the server first architecture we have in fresh with our islands approach. It would circumvent the handler -> render props passing, like you mentioned, which to me is really attractive.

Before:

```jsx
export const handler = {
  async GET(req, ctx) {
    const data = await getDataFromDatabase();
    return ctx.render({ data });
  }
}

export default function Page({data}) {
  return <App data={data} />
}
```

After:

```jsx
export default async function Page(req, ctx) {
  const data = await getDataFromDatabase();
  return <App data={data} />
}
```

Need to think some more, but first thoughts are that I really like it 👍

**Comment by marvinhagemeister** [comment]
Closing this as we shipped async route components. That allows you to pass data directly to the components.
