### ISSUE TITLE
error: Uncaught (in promise) ReferenceError: __DENO_NODE_GLOBAL_THIS_0_46_0__ is not defined

### ISSUE THREAD

**Issue by andykais** [denoland/fresh#1437]
There appears to be a problem with npm specifiers in my project. When importing this line inside my `/routes/_middleware.ts` file, 
```ts
import * as z from 'npm:zod@3.21'
```
And importing it into `main.ts` following this guide https://fresh.deno.dev/docs/examples/init-the-server, I get the following error message:
```
Check file:///home/andrew/Code/development/grob/src/grob%20dashboard/main.ts
error: Uncaught (in promise) ReferenceError: __DENO_NODE_GLOBAL_THIS_0_46_0__ is not defined
    at file:///home/andrew/.cache/deno/npm/registry.npmjs.org/zod/3.21.4/lib/index.mjs:1:18
```

**Comment by andykais** [comment]
It was my understanding that npm specifiers worked outside of deno deploy https://deno.com/blog/fresh-1.2#limited-support-for-npm-specifiers. I only plan to release this for local hosting, so deno deploy isnt a blocker. However it appears that no npm modules work inside fresh, at least on the server side.

Repro is here https://github.com/andykais/grob/tree/6f76ce343178de2782d66653cbeed721c3820e11

**Comment by bartlomieju** [comment]
This problem should be fixed by https://github.com/denoland/deno/pull/19307

**Comment by marcushultman** [comment]
Looks like this only happens when running `dev.ts`, due to the dynamic `await import(entrypoint)`. Why does fresh `dev.ts` have to proxy the import to `main.ts`? It doesn't look like it adds any functionality, and it only needs the base (`import.meta.url`) to regenerate the manifest. Maybe it would make sense for `dev.ts` to be:
```
await dev(import.meta.url);  // ensure min deno version and regenerate manifest
import './main.ts';
```
And the last line in `$fresh/dev.ts` can be dropped (`await import(entrypoint)`).

Obviously breaking change, but could make things a bit simpler in terms of debugging too?

edit:
As a workaround you can change `dev.ts` to:
```
await dev(import.meta.url, './dummy.ts');
import './main.ts';
```
And add an empty `dummy.ts` file.

edit2:
Actually, the workaround does not seem to work, as the manifest is not properly recreated.

**Comment by andykais** [comment]
thanks for digging in guys. It should be fine for me to wait on the proper fix in deno. Ill report back here when that code is released if it fixes my problem

**Comment by andykais** [comment]
Just reporting that fresh 1.3 also has this problem

**Comment by marvinhagemeister** [comment]
For anyone coming across this. It's something that needs to be addressed in Deno directly, not in Fresh. See https://github.com/denoland/deno/pull/19307

**Comment by deer** [comment]
I guess this can be closed now that 19307 was merged. I tested it with `import * as z from 'npm:zod@3.21'` and it seems to be working just fine.
