### ISSUE TITLE
Question: Update routes for static files without server restart

### ISSUE THREAD

**Issue by Spottedstorm23** [denoland/fresh#1512]
Hello,

I was wondering if it might be possible to update the routes for static files without having to restart the server?

**Situation:**
The situation I have is the following:
The app has the option to upload html-files, which are then saved in the "static"-directory.
Those files are served through an iframe on different pages.

The application is running inside a docker container, the static-dir is mounted as a volume for persistence. The uploaded files are there, when one looks into volume and container.

Yet the page remains white and the file cannot be loaded. There appears a 404 error in the console.
I think that might be due to the file not having a route.

Also when I check if the file exists using Deno.stat(), it does not throw an error, so at least Deno seems to know there is something.

After restarting the docker container and so the server, the file is served without problems.

Thats why I wanted to know if there was a way, to update the routes for the static files whenever a file is uploaded.

If I am not mistaken the app is running on fresh 1.3.0 for now.

**Comment by marvinhagemeister** [comment]
When Fresh starts it looks for all available static files and stores the routes for them in memory. These are not refreshed whilst Fresh is running. I'm a bit hesitant to change that because it means we can do route based matching without having to consult the file system and can do that completely in memory. To me that's a desirable feature to have for performance.

What about creating a route and point to your own static folder? That way we can get the best of both worlds. This would also allow you to add access control in case you don't want every user to be able to overwrite everyone else's files.

**Comment by marvinhagemeister** [comment]
Closing as it's not something we're planning to do. That said the middleware system in the upcoming Fresh 2 release is pretty flexible and folks can add their own custom routers to do such things.
