### ISSUE TITLE
Event handlers cannot be passed from server components to islands

### ISSUE THREAD

**Issue by roberto-morado** [denoland/fresh#1547]
I have the following problem.

```js
// islands/Button.tsx
export default function Button(
  props: JSX.HTMLAttributes<HTMLButtonElement>,
) {
  return (
    <button
       {...props}
    />
  );
};
```

```js
// routes/index.tsx
export default function Home() {
  return (
    <Button onClick={(e)=>{console.log(e)}}>Click</Button>
  );
};
```

Nothing happens.

This, however, works just fine: 

```js
// islands/Button.tsx
export default function Button(
  props: JSX.HTMLAttributes<HTMLButtonElement>,
) {
  return (
    <button
       onClick={(e)=>{console.log(e)}}
       {...props}
    />
  );
};
```

```js
// routes/index.tsx
export default function Home() {
  return (
    <Button>Click</Button>
  );
};
```

Why can't I pass `onClick` as a prop?

**Comment by lausuarez02** [comment]
Hey @roberto-morado,
It's never gonna work since it's not intended to work in static files such as /routes/index, javascript will run inside the island folder, that's why it is working inside 
/islands/
And not inside 
/routes/

This is a general answer but i hope it helps.

**Comment by marvinhagemeister** [comment]
Yup, like @lausuarez02 mentioned: Code inside route files only runs on the server and not in the browser. Only code inside islands will be executed in the browser. Whilst passing a pure function that doesn't reference a variable could be serialised and sent to the browser, I'm hesitant to add something like this because there it's difficult to prove that a function is really pure in JS except for simple cases.

**Comment by roberto-morado** [comment]
How can you handle dynamic interactions? I read over the resource you provided but it doesn't really tell me how to handle, for example, the change of state when a button is clicked... I'd imagine fresh offers the ability for components to be reusable, correct?

**Comment by marvinhagemeister** [comment]
I'm not sure I understand the question. The documentation has an example on how islands work here https://fresh.deno.dev/docs/concepts/islands and here https://fresh.deno.dev/docs/examples/sharing-state-between-islands . The whole point of having components is to be able to reuse them. Why wouldn't that be possible?

**Comment by roberto-morado** [comment]
For some reason the on click is not "being read" when passed from a route to an island, I was trying to keep the state on the route using a signal but I ended up passing the state to the island which made this problem go away, however I'd like to understand why I couldn't pass an on click function to the island... is not that I'm unable -- I was able to pass a function that updates state using a _middleware file successfully -- but that was a little overkill for what I was trying to do.

**Comment by marvinhagemeister** [comment]
The reason passing a function as a prop to an island doesn't work is because there is no correct technical way to do that. Islands run in the browser so to theoretically make this work there would be some way needed to serialize functions and send them to the browser. Problem is that functions can also access variables outside of their own function body. That makes it next to impossible to do this in a correct manner.

For that reason Fresh has clear distinction between islands or rather components that run in the browser and code that runs on the server. The way to pass data is to pass via props, but no functions.
