### ISSUE TITLE
Async Server Component make state `undefined`

### ISSUE THREAD

**Issue by afifurrohman-id** [denoland/fresh#1566]
```tsx
// routes/index.tsx

export default async ({ state }: PageProps) => {
 const user = state.user // undefined
 const {something} = await somePromise()

return <h1>Hello</h1>
}
```

**Comment by marvinhagemeister** [comment]
That's the expected behavior. Async route components don't receive props as a parameter. The first Argument is the `Request` instance and that doesn't have that property. Our documentation has a section about how to use them and what arguments they receive: https://fresh.deno.dev/docs/concepts/routes#async-route-components
