### ISSUE TITLE
Event listeners not getting called

### ISSUE THREAD

**Issue by rojvv** [denoland/fresh#1587]
## What

Event listeners like `onClick`, `onMouseEnter`, etc. are not getting called.

## Reproduction

1. Create an island with the following content:

```tsx
import { signal } from "@preact/signals-core";

const showButton = signal(false);

setTimeout(() => {
  showButton.value = true;
}, 2000);

export default function App() {
  if (showButton.value) {
    return (
      <>
        <button onClick={console.log}>Click Me</button>
      </>
    );
  } else {
    <></>;
  }
}
```

2. Try clicking the button when it appears and see if anything is logged into the console.

**Comment by nhrones** [comment]
You're logging nothing!  You won't see anything!
try
```
<button onClick={console.log('clicked')}>Click Me</button>
```

**Comment by rojvv** [comment]
Hmm, that just sets the `onClick` property to `undefined`.

**Comment by nhrones** [comment]
I was wrong again.  Not the first time.
Why not use IS_BROWSER rather than a timer?

**Comment by rojvv** [comment]
I’m not sure what you mean by this. Do you mean checking if the component is rendered from the browser? It’s an island. It’s always rendered from the browser.

**Comment by nhrones** [comment]
They are hydrated on the client in addition to being rendered on the server.

**Comment by nhrones** [comment]
```ts
import{IS_BROWSER}from"$fresh/runtime.ts";
 
     <button
       {...props}
       disabled={!IS_BROWSER|| props.disabled}
     />
```

**Comment by marvinhagemeister** [comment]
> You're logging nothing! You won't see anything! try
> 
> ```
> <button onClick={console.log('clicked')}>Click Me</button>
> ```

@nhrones This just calls `console.log('clicked')` when the component renders. The return value of that expression is `undefined`, so it's effectively the same as doing:

```jsx
<button onClick={undefined}>Click Me</button>
```

@roj1512 So the reason this fails is because of a hydration mismatch. The `signal()` is created as a global on the server so after waiting `2000ms` it will always be true. That signal is shared for every request that server/serverless function responds to. So the server will always send the `<button>Click me</button>` in the HTML to the browser.

Now the browser sees the HTML and tries to hydrate it. But because hydration is way quicker (a couple of ms at most) than the `2000ms` timeout the signal value in the browser is `false`. Meaning there shouldn't be a button!

- Server renders with `showButton = true`
- Browser renders with `showButton = false`

So Preact encounters a `<button>` element in the DOM and thinks: "wait this wasn't rendered by me, maybe that was inserted by a browser extension?" and simply moves around the button element. Foreign HTML elements are not a rare occurrence either. Google Translate is the most well known one and it inserts a couple of HTML elements anywhere it wants. Another example is extensions like password managers which insert their own HTML too.

The easiest fix for this is to ensure that the signal value in the client are the same values that it was rendered with. A way to ensure that is to put the signal inside the component via a `useSignal` hook.

```diff
- import { signal } from "@preact/signals-core";
+ import { useSignal } from "@preact/signals";
+ import { useEffect } from "preact/hooks";

- const showButton = signal(false);
- 
- setTimeout(() => {
-   showButton.value = true;
- }, 2000);

  export default function App() {
+   const showButton = useSignal(false);
+   useEffect(() => {
+    setTimeout(() => {
+       showButton.value = true;
+     }, 2000); 
+   }, []);

    if (showButton.value) {
      return <button onClick={console.log}>Click Me</button>;
    }
    
    return <p>no button</p>
  }
```
