### ISSUE TITLE
Setting attributes on `<html>` element

### ISSUE THREAD

**Issue by cbinzer** [denoland/fresh#1595]
Hi,

I noticed that it is not possible to use async server components with a custom render function. But why? I'm providing my own render function to set the HTML language to 'de':

```typescript
await start(manifest, {
  plugins: [kvInsightsPlugin()],
  render: (ctx, render) => {
    ctx.lang = 'de';
    render();
  },
  router: {
    trailingSlash: true,
  },
});
```

Is there maybe another way to set the language?

**Comment by pazguille** [comment]
Same issue here! Also I need to set the `ctx.lang` based on pathname (domain/mx-store, domian/br-store)

**Comment by marvinhagemeister** [comment]
I kinda want to deprecate the custom render option at some point in the future. It breaks a bunch of assumptions within Fresh at the moment.

My plan for being able to set attributes on `<html>` is to expose that in `_app.tsx` rather than letting Fresh add that. Kinda similar to how remix does it.

So you'd do all the language detection things inside a middleware, pass that to `ctx.state` and render that directly to `<html>` yourself:

```tsx
// _app.tsx
// Not possible today, but hopefully soon
export default function App({ Component, state }: AppProps) {
  return (
    <html lang={state.lang}>
      <head>
        ...
      </head>
      <body>
        <Component />
      </body>
    </html>
  );
}
```

I got the fundamentals for that ready in `preact-render-to-string` and need to mainly integrate it with Fresh now.

**Comment by cbinzer** [comment]
Ok, that would be great. So I'am waiting with my refactoring work. Thank you for that :-)
