### ISSUE TITLE
Head component: double quotes in CSS strings are escaped

### ISSUE THREAD

**Issue by iugo** [denoland/fresh#1779]
In the Head component, double quotes in CSS strings are escaped. This causes CSS code in the <style> tag to not work.

```html
import { Head } from "$fresh/runtime.ts";

<Head>
  <style>
    @font-face {
      font-family: "fontname";
      src: url(data:font/woff2;charset=utf-8;base64,${woff2}) format("woff2");
    }
  </style>
</Head>
```

The CSS code in this example will not work because the double quotes are escaped. To fix this, the Head component should not escape double quotes in CSS strings.

**Comment by marvinhagemeister** [comment]
Any text node is by default escaped during rendering. Reason for that it's quite easy to open yourself up for malicious injection attacks by accident.

For example if we wouldn't escape text nodes, the snippet you provided would be vulnerable to the following injection attack:

```tsx
// Malicious string
const woff2 = `asdf) format("woff2"); }</style><script>alert("injection attack");</script><style>foo { ignore: url("#"`;

<style>
  @font-face {
    font-family: "fontname";
    src: url(data:font/woff2;charset=utf-8;base64,${woff2}) format("woff2");
  }
</style>
```

Without escaping this successfully executes the maliciously inserted string:

<img width="575" alt="Screenshot 2023-09-15 at 12 20 06" src="https://github.com/denoland/fresh/assets/1062408/690912dd-abf1-460d-98f2-ef48653c4c9d">

So to not open up users to such attacks, we escape text by default.

## Workaround

The problem is that during rendering it's impossible to detect if a string is malicious or not. Sometimes you want to render the original string as is though like in your example. For these scenarios we have an escape hatch that allows you to bypass the escape mechanisms.

```tsx
const cssString = `
  @font-face {
      font-family: "fontname";
      src: url(data:font/woff2;charset=utf-8;base64,${woff2}) format("woff2");
  }`

<style dangerouslySetInnerHTML={{__html: cssString}} />
```

Make sure though that you never ever pass unsanitized user input into that though, because otherwise malicious actors can exploit that in the same way as demonstrated earlier.

**Comment by iugo** [comment]
I noticed that https://github.com/preactjs/preact-render-to-string/issues/176#issuecomment-1648751707 mentions this solution, which ultimately is a Preact issue, rather than a Fresh issue. If the variable parameters come from the user, there might be security concerns. However, for server-side rendering, the CSS that needs to be handled is generally safe information processed by the backend, so not escaping it still makes sense. Thank you for your response.
