### ISSUE TITLE
Component Property named "key" does not work

### ISSUE THREAD

**Issue by kitsonk** [denoland/fresh#1836]
I am not sure exactly where the issue lies (Fresh or Preact) but using a component property named `key` will cause the value inside the component to always be `undefined`.  I spent a day trying to figure out what I was doing wrong, only to realise the root of the issue.

I have a re-production here: https://github.com/kitsonk/fresh-key-issue/blob/main/islands/Counter.tsx. I simply renamed the `count` property from a scaffolded application to `key` and now the application does not work.

**Comment by marvinhagemeister** [comment]
The `key` property is special because it is reserved for keyed children reconciliation. This is necessary in any virtual-dom based framework (=Preact, React and others), because otherwise there would be no way to include information about ordering when comparing child nodes. Including that information in the reconciler is necessary for sorted/filtered list UIs to work. It's therefore a special framework specific property that is not forwarded to the component.

There is some more information here: https://preactjs.com/tutorial/08-keys/
