### ISSUE TITLE
Docs: Merge data fetching pages

### ISSUE THREAD

**Issue by pnadj** [denoland/fresh#1974]
As per '[Fetching Data](https://fresh.deno.dev/docs/getting-started/fetching-data)' section in the docs, In order to fetch data, the route component must be asynchronous. Unfortunately when doing so the parameters are overwritten and you no longer have access to the props.

`/routes/[user].jsx`
```
const User = (props) => {
    console.log(props);
```

Compared to

`/routes/[user].jsx`
```
const User = async (props) => {
    console.log(props);
```

Is there a correct way for handling this I'm maybe missing?

**Comment by deer** [comment]
Hi @pnadj, I think there's a bit of confusion here. I've created some complete examples to help clarify things:
`standard.tsx`
```tsx
import { Handlers, PageProps } from "$fresh/server.ts";

export const handler: Handlers = {
  GET(_req, ctx) {
    const complicatedData = "asdf";
    return ctx.render(complicatedData);
  },
};

export default function Home(props: PageProps<string>) {
  console.log(props);
  return props.data;
}
```
In this case, `PageProps` is defined like this:
```tsx
export interface PageProps<T = any, S = Record<string, unknown>> {
  /** The URL of the request that resulted in this page being rendered. */
  url: URL;

  /** The route matcher (e.g. /blog/:id) that the request matched for this page
   * to be rendered. */
  route: string;

  /**
   * The parameters that were matched from the route.
   *
   * For the `/foo/:bar` route with url `/foo/123`, `params` would be
   * `{ bar: '123' }`. For a route with no matchers, `params` would be `{}`. For
   * a wildcard route, like `/foo/:path*` with url `/foo/bar/baz`, `params` would
   * be `{ path: 'bar/baz' }`.
   */
  params: Record<string, string>;

  /**
   * Additional data passed into `HandlerContext.render`. Defaults to
   * `undefined`.
   */
  data: T;
  state: S;
}
```
So far this is the old standard approach. Let's try an async route. Might as well make it dynamic, just to reduce the number of examples from three to two.
`[asyncExample].tsx`
```tsx
import { RouteContext } from "$fresh/server.ts";

export default async function Page(_req: Request, ctx: RouteContext) {
  const complicatedData = "asdf";
  console.log(ctx);
  return complicatedData;
}
```

Note how `ctx` is now a `RouteContext` instead of `HandlerContext` from before. I didn't cover that, so I'll include both types here for completeness:
```tsx
export interface HandlerContext<
  Data = unknown,
  State = Record<string, unknown>,
  NotFoundData = Data,
> extends ServeHandlerInfo {
  params: Record<string, string>;
  render: (
    data?: Data,
    options?: RenderOptions,
  ) => Response | Promise<Response>;
  renderNotFound: (data?: NotFoundData) => Response | Promise<Response>;
  state: State;
}

export type RouteContext<T = any, S = Record<string, unknown>> = {
  /** @types deprecated */
  localAddr?: Deno.NetAddr;
  remoteAddr: Deno.NetAddr;
  renderNotFound: (data?: T) => Response | Promise<Response>;
  url: URL;
  route: string;
  params: Record<string, string>;
  state: S;
  data: T;
};
```

The key thing is the similarity between `PageProps` and `RouteContext`:
* `PageProps` has: url, route, params, data, state
* `RouteContext` has: url, route, params, state, data

So everything you're familiar with on `props` is available on `ctx` in the async route. I can highly recommend typescript to help make these things more clear.

Do you have recommendations on how the documentation can be improved to make this more clear?

**Comment by pnadj** [comment]
Thanks @deer, I agree Typescript would have cleared that up faster. I ended up finding the [Data Fetching](https://fresh.deno.dev/docs/concepts/data-fetching) guide with the old standard after the fact.

I think unifying the [Data Fetching](https://fresh.deno.dev/docs/concepts/data-fetching) and [Fetching data](https://fresh.deno.dev/docs/getting-started/fetching-data) guides into one page would fix up any confusion. Not much has to be changed, just a title on top of each 'Standard 1' and 'Standard 2' or something similar IMO

**Comment by marvinhagemeister** [comment]
Reopening so that we can keep track of need for docs update
