### ISSUE TITLE
npm import for tailwind has a leading `/`

### ISSUE THREAD

**Issue by sylc** [denoland/fresh#2128]
I'm not sure, but It seems to me that the leading `/` in the tailwind npm import looks like a typo i.e `npm:/` should be `npm:`

```diff
"tailwindcss": "npm:tailwindcss@3.3.5",
- "tailwindcss/": "npm:/tailwindcss@3.3.5/",
+ "tailwindcss/": "npm:tailwindcss@3.3.5/",
- "tailwindcss/plugin": "npm:/tailwindcss@3.3.5/plugin.js"
+ "tailwindcss/plugin": "npm:tailwindcss@3.3.5/plugin.js"
```

https://github.com/denoland/fresh/blob/main/src/dev/imports.ts#L26

Or is this on purpose ?

thanks for the added support of tailwindcss 🚀 !

**Comment by marvinhagemeister** [comment]
Yes that slash after the `npm:` prefix is intentional. It's a bit of an oddity because internally deno treats it as an url and has a special case for import mappings without any slashes. I've brought this up here internally with the CLI team, and it seems like there is a growing mindshare of allowing getting rid of the first slash. But so far no action on that though.

Happy to hear that you enjoy the tailwindcss plugin 👍
