### ISSUE TITLE
Upgrading Fresh to 1.6 causes all routes and components to throw errors

### ISSUE THREAD

**Issue by andrewfgarrison** [denoland/fresh#2135]
I have upgraded both Deno and Fresh to their newest versions on my computer, but upon doing so, all routes and components throw the following error:
`Uncached or missing remote URL: https://esm.sh/preact@10.19.2/jsx-runtime`
In addition, every JSX element in the file throws this error as well.
`JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`
I assume the solution is to manually import the URL above, but because JSX no longer seems to be importable, I am not sure how to do this.

![image](https://github.com/denoland/fresh/assets/64180300/d131a736-401b-4b52-b437-4cbbe693d20a)

**Comment by marvinhagemeister** [comment]
It's an issue with Deno itself that seems to sometimes pop up. We haven't found the root cause of it yet. The workaround seems to be to invoke `deno check main.ts` once to refresh the internal caches. That resolves it.

We're collecting info about that bug over here: https://github.com/denoland/deno/issues/20582
