### ISSUE TITLE
node:xxx CORS error

### ISSUE THREAD

**Issue by tetsuya28** [denoland/fresh#2207]
With islands component like following, I got CORS error.
Why Deno or fresh accesses to `node:xxx`, such as `node:prcess`, `node:url`, `node:tls`, etc.
And, how to fix this error.

```ts
export default function Sidebar() {
	useEffect(() => {
		(async () => {
			try {
	 			const client = new MyClient();
                                 ...
			} catch (err) {
				console.error(err);
			}
		})()
	}, [])

// Just set url in constructor
export class MyClient {
  apiBaseUrl: string;

  constructor() {
    this.apiBaseUrl = config.BACKEND_ENDPOINT; // http://localhost:8080
  }
}
```

![s 178](https://github.com/denoland/fresh/assets/11973270/fb2b5d90-4d9b-412c-a364-5f69ff1106af)
![s 179](https://github.com/denoland/fresh/assets/11973270/b9de1976-2192-4448-9c7b-15432f6f29cf)

fresh: v1.6.1

**Comment by marvinhagemeister** [comment]
Sounds like you're pulling in code into your islands which is not meant to run in the browser, but rather on the server. We can't help you more based on the snippet you provided because the culprit is likely the various imports in that island files. Or the files that are imported in the island import another file that in turn pulls in server-only dependencies.

**Comment by tetsuya28** [comment]
I found server-only dependencies from imported file. And, when remove the code, the code works fine. Thanks.
