### ISSUE TITLE
`useContext()` hook returns nothing when join in one component with the context provider

### ISSUE THREAD

**Issue by ooker777** [denoland/fresh#2251]
Say I have this **`index.tsx`**:
```js
import UsernameProvider from "../islands/User.tsx";


export default function App() {
  return (
    <><UsernameProvider /></>
)}
```
And this **`User.tsx`** file, in which the `useContext()` hook is split into a separate function:
```js
import { useContext } from 'preact/hooks';
import { createContext } from 'preact'

const Username = createContext()

export default function UsernameProvider({children}) {
  return (
    <Username.Provider value="value"><User />
    </Username.Provider>
  );
}
function User() {
  const username = useContext(Username); 
  return <>U{username}</>
}
```
then it returns `Uvalue` as expected.

However if they are joined in one component:
```js
export default function UsernameProvider() {
  const username = useContext(Username); 
  return (
    <Username.Provider value="value">
      U{username}
    </Username.Provider>
  );
}
```
then it only returns `U`.

Is this a bug?

Related #983, #2249

**Comment by marvinhagemeister** [comment]
This is not a bug but the way context works. Basically, what happens is that the `useContext` value tries to read the context value but no provider was found in any of the parents of the current component. Since no parent context provider for this context was found Preact falls back to the default value. The default value can optionally be passed to `createContext` like so:

```tsx
// Passing a default value:
const MyContext = createContext(someDefaultValue);

// No default value set, will default to `undefined`
const MyContext = createContext()
```

In your case the context is constructed without any argument, so the default value will be `undefined`.

```ts
const Username = createContext()
```

Then in your combined code snippet the context is read immediately. Since no provider has been present it will fall back to the default value which is `undefined`:

```tsx
export default function UsernameProvider() {
  // No context provider found in any of the parents of this component,
  // will fall back to the default value. Since no default value is
  // set the context's default value is `undefined`
  const username = useContext(Username); 
  
  // At this point the variable `username` is `undefined`
  
  // After reading from the `Username` context, a context provider
  // is created here to pass the value "value" for ever children of
  // this component. Note that this has no effect on the currently
  // running component. Context values are always read from parent
  // components only.
  return (
    <Username.Provider value="value">
      U{username}
    </Username.Provider>
  );
}
```

At this point the `username` variable is `undefined` and rendering `undefined` is always being converted to an empty string by Preact. So essentially the code is rendering `"U" + ""` which will end up as just `"U"`.
