### ISSUE TITLE
imported revive function and islands from script into browser is not taking basepath into account

### ISSUE THREAD

**Issue by Bramart** [denoland/fresh#2326]
Trying to add a basepath `/neoplayer/` to a deno fresh app, with another app (node project) at the root.
Basepath is setup in deno fresh config and import in main.ts. Everything works fine except the islands.

In the html file loaded in the browser, basepath is applied to src and href (like said in the docs)

![image](https://github.com/denoland/fresh/assets/96910886/fec9144d-22fb-4ecf-b39c-ee79751d973b)

At the end there is a script that imports the revive function from main.js and islands from their own js files. Those imports are not prefixed with the basepath. 

![image](https://github.com/denoland/fresh/assets/96910886/697dd49d-4d36-47c6-b8d3-53724c9c3b06)

So the request is on the root and the js is not load which leads me to this error in the browser because my root application returns a 404 error page :

![image](https://github.com/denoland/fresh/assets/96910886/19389527-d649-420e-a24a-5e695b5bee84)

deno version : 1.36.1
deno fresh version : 1.6.5

**Comment by deer** [comment]
Hi @Bramart, I coded this feature. There is a test for it here:
https://github.com/denoland/fresh/blob/46eaef0181cba60a5e0284f58b24925e762c7784/tests/base_path_test.ts#L130
which uses:
https://github.com/denoland/fresh/blob/46eaef0181cba60a5e0284f58b24925e762c7784/tests/fixture_base_path/routes/islands.tsx#L4

Can you provide some more details? They should all be redirected like this:
<img width="1018" alt="Screen Shot 2024-02-20 at 15 30 33" src="https://github.com/denoland/fresh/assets/1494757/e04fe1a4-008a-4b28-99be-49716651e763">

I'll need more information (ideally a repository which easily reproduces the problem) in order to proceed, because from my side it's working. I guess the test is missing something though.

**Comment by Bramart** [comment]
Hi, here is a fresh repo I just create and still facing the same issue with : https://github.com/Bramart/fresh-project (deno fresh example with basepath config ...)

In local, it works for me too, they are redirected (I have interactivity) :

![Capture d’écran du 2024-02-20 17-45-31](https://github.com/denoland/fresh/assets/96910886/2c413f8b-79d4-4fdb-b29e-1ee441303bae)

But once deployed behind another app, they are not (and no interactivity) : 

![Capture d’écran du 2024-02-20 17-44-44](https://github.com/denoland/fresh/assets/96910886/ac48c2c1-dfb2-4940-a6cb-0dd81c8f071a)
![Capture d’écran du 2024-02-20 17-44-58](https://github.com/denoland/fresh/assets/96910886/c5c41e13-5630-4949-a5be-d96cd00ef473)

In local, the redirection is made by fresh because fresh manage the whole app, but once deployed to a basepath and next to another app, those requests just hit on the root application like they are supposed to, no ?

**Comment by deer** [comment]
You are very right there. I have a fix and I'm working on a test. Oops 😅
