### ISSUE TITLE
docs: double `the` word on `Plugins` section

### ISSUE THREAD

**Issue by Iuriiiii** [denoland/fresh#2518]
Hi, A little grammar error there:

![image](https://github.com/denoland/fresh/assets/85367841/1af80f44-d852-4a6e-ac9d-0783c0d3f3ca)

It can be fixed easily just removing the duplicated `the` word in the file `docs/latest/concepts/plugin.md:83:29`

**Comment by Iuriiiii** [comment]
Just in case, i tried to open a pr, but i couldn't due a git error (permission denied)

**Comment by marvinhagemeister** [comment]
@Iuriiiii The way Pull Requests work in GitHub or elsewhere is that you fork the repository, push your changes to a branch in your fork and the create a pull request from your fork that targets the original repository. The permission error you're seeing means that you tried to push the branch into this repository instead of your fork. Create a fork first.

**Comment by Iuriiiii** [comment]
> @Iuriiiii The way Pull Requests work in GitHub or elsewhere is that you fork the repository, push your changes to a branch in your fork and the create a pull request from your fork that targets the original repository. The permission error you're seeing means that you tried to push the branch into this repository instead of your fork. Create a fork first.

JAJAJAJAJA You're right!! So sorry, incredible that you have to explain me something so basic, long time ago since I done a PR to a open source project, my bad 😬
