### ISSUE TITLE
Document how to use fresh in a sub-directory (e.g `src/`)

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#257]
### Discussed in https://github.com/lucacasonato/fresh/discussions/253

<div type='discussions-op-text'>

<sup>Originally posted by **o-az** June 18, 2022</sup>
Moved `islands`, `routes`, `fresh.gen.ts`, `dev.ts` and `main.ts` to `src` directory.

Updated `start` task in `deno.json` to: `deno run -A --watch=src/static/,src/routes/,src/islands/ --no-check src/dev.ts`.

Project runs and routes work but this error is consistently logged:
![CleanShot 2022-06-18 at 08 40 01](https://user-images.githubusercontent.com/23618431/174440261-6b6b0b03-9c12-4ecb-a3bb-2a025701e871.png)

I'm trying to avoid this error. Is there a proper way to have a `.src/` directory or is it not possible as of now?</div>

**Comment by o-az** [comment]
I think my problem was not being able to run `fresh manifest` in the cli. So when I made directory changes it didn't pick it up right away. Just curious, is `fresh manifest` supposed to run automatically or do I need to install anything? I do have Deno CLI installed and I scaffolded fresh app using the documented command.

**Comment by lucacasonato** [comment]
The `fresh manifest` command does not exist anymore (the entire fresh CLI has been removed).

**Comment by o-az** [comment]
when making updates like directory structure changes how are we supposed to make fresh recognize those updates?

**Comment by lucacasonato** [comment]
Fresh does it itself now (see //www/dev.ts in this repo). https://fresh.deno.dev/docs/getting-started/create-a-project elaborates on what the dev.ts file does.

**Comment by greym0uth** [comment]
Looking at [this line](https://github.com/denoland/fresh/blob/10094f894728e2074e5c10b678d8328258159310/src/dev/mod.ts#L145) it looks like if your `dev.ts` lives in `src/dev.ts` and your `start` task points there (`deno run -A --watch=src/static/,src/routes/ src/dev.ts`) it'll look for the routes directory relative to that entrypoint's base directory (i.e. `<project_root>/src/routes` instead of `<project_root>/routes`). I tested this with locally w/ dev and it works just fine but there may be more to consider for deployments.

**Comment by greym0uth** [comment]
The error seen look specifically related to invalid MIME type configuration in server 
![Screen Shot 2022-07-06 at 12 26 31 PM](https://user-images.githubusercontent.com/5057468/177627626-70db2723-2fda-4850-89cb-5520c4089f3b.png)

**Comment by greym0uth** [comment]
Alright so moving the `import_map.json` into the `src/` directory and updating the `deno.json` to point the import map to `"importMap": "./src/import_map.json"` fixes the errors. It looks like the islands imports are looking at `../import_map.json` to get the import map and was failing on request because it couldnt load the dependencies; might be a bug there @lucacasonato but I can spin up an issue specifically around that and do a bit more digging. I'm working on a PR now for the documentation piece on using the `src` project layout right now.
