### ISSUE TITLE
No lock file when installing

### ISSUE THREAD

**Issue by nickytonline** [denoland/fresh#2734]
I noticed that Fresh has `"lock": false` in it's deno.json file. Based on https://github.com/denoland/deno-gfm/issues/47#issuecomment-1460872019, I understand the reasoning. TLDR; esm.sh modules are not guaranteed to be immutable.

I'm wondering why Fresh, Preact and the [standard library](https://jsr.io/@std) aren't loaded using the `jsr:` (or `npm:` in the case of Preact) specifier, which would allow the lock file to be enabled by default as all dependencies would be immutable then.

If this is something that just hasn't been addressed yet, happy to put up a pull request for it.

**Comment by nickytonline** [comment]
It looks like [Fresh doesn't have a stable release on jsr.io](https://jsr.io/@fresh) yet, so I guess that's the reasoning for now?

**Comment by marvinhagemeister** [comment]
Going forward we're always encouraging to use a lock file. During the 1.x we didn't have one because external http dependencies like from esm.sh frequently changed the transpilation output and causes checksum mismatches. We got too many support requests related to that to handle at that time. With the move to JSR and support for npm dependencies this is not an issue anymore. It's mostly an issue with http dependencies.

**Comment by nickytonline** [comment]
Cool cool. Thanks so much for the quick reply Marvin!
