### ISSUE TITLE
Website readme is out of date 

### ISSUE THREAD

**Issue by UmbrellaCrow612** [denoland/fresh#451]
The command 

deno -A —watch main.ts

should be replaced with 

dev.ts

**Comment by nikableh** [comment]
I assume you are talking about `/www/README.md` file in this repository. This is already being fixed by https://github.com/denoland/fresh/pull/448.

`deno run -A --watch=static/,routes/ dev.ts` is already the default command for newly generated projects.

By the way, I would suggest you format the code in issues with \` `. You can also use \``` ``` for multi-line blocks of code. This really helps by making the code more readable.

**Comment by UmbrellaCrow612** [comment]
Thanks
