### ISSUE TITLE
Property 'writable' does not exist on type 'Writer & Closer'.

### ISSUE THREAD

**Issue by thedatagata** [denoland/fresh#474]
Hello - I ran `deno run -A -r https://fresh.deno.dev my-project` and hit the error 

`error: TS2339 [ERROR]: Property 'writable' does not exist on type 'Writer & Closer'.
  await raw.pipeTo(proc.stdin.writable); at https://deno.land/x/fresh@1.0.1/src/dev/mod.ts:127:31`

**Comment by nikableh** [comment]
Everything works fine. Could you please provide an output of `deno --version` and `which deno` commands?

**Comment by tsklxiv** [comment]
I also got this problem and are using Deno 1.13.1

```
deno 1.13.1 (release, x86_64-unknown-linux-gnu)
v8 9.3.345.11
typescript 4.3.5
```

For `which deno`:

```
$ which deno
/home/firefly/.deno/bin/deno
```

**Comment by tsklxiv** [comment]
Oh, it turns out that I have a `deno` collision between the `deno` installed in Linuxbrew and the old `deno` I installed a few months ago. Removed the old one makes it work perfectly.

If you are having this problem, try updating your Deno to 1.23.0 or higher, or removing duplicated binary (if you found any) to avoid collision.

**Comment by iamsahilsonawane** [comment]
@thedatagata Can you try out the above solution, if it works you can close this issue
