### ISSUE TITLE
Is css modules available?

### ISSUE THREAD

**Issue by ahmetcanaksu** [denoland/fresh#526]
Hi! 

Im trying to port my nextjs app to fresh but when I import css module with import in islands I get an error. I know it must be preact's thing but I couldn't find anything. Am I missing something?

<img width="805" alt="resim" src="https://user-images.githubusercontent.com/26122392/179948454-371a09cf-0c89-4fcb-b916-bcc20534f480.png">

By the way: Thanks for framework! Loved it <3

**Comment by iamsahilsonawane** [comment]
This is how you import static assets. Make sure to add the file in the `static` folder.

```js
/** @jsx h */
import { h } from "preact";
import { asset, Head } from "$fresh/runtime.ts";
import { AppProps } from "$fresh/src/server/types.ts";

export default function App({ Component }: AppProps) {
  return (
    <html data-custom="data">
      <Head>
        <title>Fresh</title>
        <link rel="stylesheet" href={asset("style.css")} />
      </Head>
      <body class="bodyClass">
        <Component />
      </body>
    </html>
  );
}
```

**Comment by ahmetcanaksu** [comment]
You mean this is the only way? Css modules would have been great. I really had enough of css's global namespace

**Comment by crowlKats** [comment]
importing CSS isnt part of either the ES or HTML spec, so importing is not possible

**Comment by dancxjo** [comment]
This is sad and makes using Fresh a no-go for me. CSS isolation in web components is important.

**Comment by binyamin** [comment]
@dancxjo 
> CSS isolation in web components is important.

By "web components", I assume you're referring to true Web Components (the [Custom Elements API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Components)), and not JSX components. The shadow dom provides isolation by default, along with `:host` and `:host-context()` for scoping your CSS.

**Comment by v1rtl** [comment]
Are there any plans for providing CSS classnames isolation anyhow else?

**Comment by marvinhagemeister** [comment]
@talentlessguy The plan is to support CSS modules, but there is no ETA yet, as there is some work needed before that to make this possible.

**Comment by v1rtl** [comment]
@marvinhagemeister what kind of work is needed to be done? can I help with integrating it anyhow?

**Comment by predaytor** [comment]
waiting.. 👀

**Comment by welpie21** [comment]
I would like to see CSS modules as well. I've used it for quite some time in react projects. There is a typescript plugin which allows you to have type safety over css modules and makes autocomplete possible. It would be nice to see it back in fresh. Would be nice if people can opt-in this kind of feature.

**Comment by webbower** [comment]
I'm also here looking for CSS Modules support in Fresh. It's my favorite CSS-in-JS solution. 

The underlying issue is that only certain kinds of files can be `import`ed as ESM files natively: primarily JS and then also JSON with the [import attributes syntax](https://docs.deno.com/runtime/fundamentals/modules/#import-attributes). CSS files of any kind are not currently supported natively with static `import`s. The way other frameworks like Next accomplish CSS modules is the same way it allows importing image paths and other file types: bundlers like Webpack and Rollup. One of the foundational capabilities of those is to apply special processing for `import` statements files. That's `css-loader`, `file-loader`, and the rest. Even transpiling newer JS features to older code and JSx component files is handled by specially processing JS and JSX files with Babel.

So the lack of CSS Modules support in Fresh is (presumably) because the Fresh AOT compiler doesn't handle processing imported CSS Module files. It would have to:

1. Detect the `import styles from './Component.module.css';` in files
2. Specially process the referenced CSS file as a CSS Modules file
3. Replace the `import` statement with a generated object of generated CSS classes from the CSS module classes assigned to the bound variable from the import statement (`styles`)
4. Inject the processed CSS Module code either into the DOM during dev mode in `<style>` tags or collectively dump the accumulated CSS Module output into one or more compiled CSS files that are then `<link>`ed in the finally generated base HTML file.

So this would likely be an AOT compile task/plugin, like transpiling JSX into plain JS. I wonder if it's possible today as a community effort, but I suspect it's worth waiting until all the big changes are done with Fresh 2 before embarking on making a POC for this.
