### ISSUE TITLE
Introduction page point intelligible

### ISSUE THREAD

**Issue by himanshu007-creator** [denoland/fresh#546]
![image](https://user-images.githubusercontent.com/65963997/180829660-28df2ecd-63dd-4256-880e-bbdf06d6499c.png)

In the last point [here](https://fresh.deno.dev/docs/introduction), 
<b>File-system routing à la Next.js</b>

some users [like me] do not understabd it in first go, unless we translate it online. Therefore having a simple english line might work.
<b>File-system routing as in Next.js</b>

Would like community's take on this. Thanks!

**Comment by himanshu007-creator** [comment]
Hi @bartlomieju , shall i raise a draft PR?

**Comment by mr-mobster** [comment]
What’s unintelligible about it? The “a la” expression has been used in English for the last few hundred years. I do not understand why one needs to “simplify” an already simple and concise phrase.

**Comment by himanshu007-creator** [comment]
> What’s unintelligible about it? The “a la” expression has been used in English for the last few hundred years. I do not understand why one needs to “simplify” an already simple and concise phrase.

Hi @mr-mobster, you made your point, but what about the people who do not have English as their native language or just know a working level english. They are unable to comprehend to this point, unless they see a lot of netflix or other media where they might get to know this **French** phrase. Therefore i find the cause of issue more clear now. Hope this comment helps in making documentation more readable.
Docs should be made as-easy and as-understandable as possible to accomodate diverse people. What's the use of fancy terms and phrases if it costs extra googling efforts for users?

**Comment by mr-mobster** [comment]
Well, given that English has a healthy dose of Old Normal French substrate, I don't see any harm in using a little bit of French  here. 

But in all seriousness, while inclusivity and clarity should be the upmost priority for documentation, I strongly disagree with  your sentiment. If a person has only a limited level of English, they can use this opportunity to learn a new phrase and expand their knowledge. But it's nonsensical to avoid common, popular constructions of the modern English language just because someone on the internet might not immediately know what they mean.  The writing style used by the Fresh documentation is passionate, fun and informal, which is great and reFreshing. Please, let's not make it boring and dry for no reason at all.

**Comment by himanshu007-creator** [comment]
@mr-mobster  that's a strong reason, thanks for bringing it out. For now i guess the issue sieze to exist :) good day!
