### ISSUE TITLE
ReferenceError: h is not defined

### ISSUE THREAD

**Issue by xinha-sh** [denoland/fresh#767]
The website is crashing because h is not found. 
<img width="976" alt="Screenshot 2022-09-13 at 10 11 13 PM" src="https://user-images.githubusercontent.com/107257599/189958875-0338bad6-2144-4d02-816d-ffe2481d434d.png">

**Comment by xyntechx** [comment]
I think you're facing this error because they removed the `/** @jsx h */` line in Fresh v1.1.x! So I think removing that line from all your files will solve the issue. When updating Fresh, they should've prompted you to allow them to automatically clean your files (after running the `deno run -A -r https://fresh.deno.dev/update .` command.

**Comment by xyntechx** [comment]
I think you're facing a similar issue as https://github.com/denoland/fresh/issues/734 😁

**Comment by xinha-sh** [comment]
Closing in favor of #734
