### ISSUE TITLE
HTML validation issues with island tags

### ISSUE THREAD

**Issue by dirkjonker** [denoland/fresh#838]
Check any fresh-generated HTML with islands and you are likely to find a couple of issues with the [w3 validator](https://validator.w3.org). It seems fresh is wrapping islands in comment tags. The opening tag is a valid HTML comment, however the closing tags for the `<!--fresh-` tags are invalid HTML.

Current versions of Chrome and Firefox seem to be able to deal with this, but this doesn't mean other clients will too, or that it won't cause any issues in the future or in weird edge cases.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/11753054/195520671-1fd3cdad-0b88-4f77-bd62-289acc024568.png">

**Comment by dirkjonker** [comment]
It seems like this may be caused by preact/preact-render-to-string not knowing (how to deal with) HTML comments. See PR I opened in preact-render-to-string above.

**Comment by lucacasonato** [comment]
> but this doesn't mean other clients will too

No, the parsing of HTML is standardised, and all compliant implementations of the HTML spec will parse this as a comment. This is why this is handled correctly by all browser implementations.

Here are the details:

1. `<` tells the HTML parser to go into ["tag open state"](https://html.spec.whatwg.org/#tag-open-state)
2. `/` tells the HTML parser to go into ["end tag open state"](https://html.spec.whatwg.org/#end-tag-open-state)
3. The `!` is an invalid tag name character, which forces the HTML parser to go into the [bogus comment state](https://html.spec.whatwg.org/#bogus-comment-state)

Even though this is not semantically valid HTML, all compliant parsers will parse `</!` ... `>` as a HTML comment.


I welcome your PR because it removes the w3c validator error though. But the current emit will parse correctly in all valid HTML parsers :)

**Comment by dirkjonker** [comment]
I learned something new today, thanks! At least it's good to know this will not cause any real issues. I always get a bit anxious when I see validation errors, sometimes they lead to weird behavior because the spec is just... weird in some cases, and browsers will always do their best to keep on working despite HTML that is breaking the spec.

**Comment by PRO-BROS** [comment]
Learned new things from here but still lean more from [here](https://prhocoding.com/)
