### ISSUE TITLE
spa using fresh

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/fresh#846]
I think it shoud be possible to build spa using fresh. I know building spa isn't main goal for fresh but I hope fresh will be most common way for building web interface( seo friendly or not). the question now is how build spa using fresh? is there Link component build in fresh like in nextjs ?

**Comment by bjesuiter** [comment]
I also like this idea. 

I try to use fresh with solidjs, I simply want to be able to ship my own js down to client, similar to astro (though astro not being fully available on deno, only as compile target). 

Is there something planned or how could I send my own js easily to client?

**Comment by billybimbob** [comment]
Given that Fresh utilizes Preact for its rendering, I've had success using Preact-compatible client-based routers. some options include [preact-router](https://github.com/preactjs/preact-router), [preact-iso](https://github.com/preactjs/wmr/tree/main/packages/preact-iso), and [wouter](https://github.com/molefrog/wouter). I find that wouter worked the best with Fresh since wouter allows for server-side rendering. Keep in mind that in order for Fresh to ship the js, the components should reside in the `islands` folder.

**Comment by kylewelsby** [comment]
I'm trying to find a solution to use Fresh and keep an island of content persistent between page loads.  (e.g. a music player)

I've found [Swup.js](https://swup.js.org/) works okay until there's interactivity required, as all JavaScript listeners are unloaded.

**Comment by khwalkowicz** [comment]
@billybimbob The other two libraries also work with SSR.
I would suggest preact-router as wouter doesn't seem to be actively maintained and preact-router is maintained by, well, the preact team.
Simply import `import { Router } from "https://esm.sh/preact-router@4.1.0?deps=preact@10.11.2";` inside an island component and pass it an url prop when it's being rendered on a server, i. e.
```
/* routes/[...path].tsx */
const Page = (props: PageProps) => (
  <div>
    <IslandWithRouter url={props.url.pathname} />
  </div>
);

export default Page;

/* islands/IslandWithRouter.tsx */
import { Router } from "https://esm.sh/preact-router@4.1.0?deps=preact@10.11.2";

const IslandWithRouter = ({ url }: { url: string }) => (
  <Router url={ur}>
    /* your routes */
  </Router>
);

export default IslandWithRouter;
```

Note the use of the wildcard route (`[...path].tsx`) ;)

**Comment by billybimbob** [comment]
@khwalkowicz ah whoops, good catch. I was basing the SSR capabilities of `preact-router` on their doc pages and didn't realize that `Router` could take `url` as a prop. `preact-router` is probably the best option then.

> The other two libraries also work with SSR.

Would you be able to show an example on how to do SSR with `preact-iso`? I feel like that library would be the best option because of its async capabilities. When I tried it out however, the `LocationProvider` component does not accept `url` as a prop (based on the typescript defs).

**Comment by khwalkowicz** [comment]
@billybimbob I also stand corrected then - despite the typescript typings I can clearly see that the `LocationProvider` is in fact taking `url` as a prop, thus my confusion. Unfortunately though `LocationProvider` also requires the `location` object which is undefined in the server context, which throws an error (and one cannot easily use a different `LocationProvider` component). It's interesting, as the docs for `preact-iso` clearly mention prerendering of the router here (https://github.com/preactjs/wmr/tree/main/packages/preact-iso#routerjs). This is a whole different discussion though so I don't think this issue is a good place to discuss this.
Anyways, it seems like `preact-router` is a way to go IMO.

(offtop: kudos on your fresh-music app, very good lookin and a very clean repository)

**Comment by rschristian** [comment]
> Unfortunately though LocationProvider also requires the location object which is undefined in the server context,

Only if you don't patch it. You can see how we do this to prerender WMR apps (which all use `preact-iso`) here: https://github.com/preactjs/wmr/blob/main/packages/wmr/src/lib/prerender.js

**Comment by rojvv** [comment]
Did anyone have this working?

**Comment by rojvv** [comment]
I built and published an SPA example for you!

Source code: https://github.com/roj1512/fresh-spa
Try it out: https://fresh-spa.deno.dev

**Comment by carlassmann** [comment]
When you want to develop an SPA the `fresh` way, maybe you want the same ergonomics while building the SPA.  Mixing Client and Server-side rendering has its pitfalls.

In [ccssmnn/relaxed-spa](https://github.com/ccssmnn/relaxed-spa) (demo: [https://relaxed-spa.deno.dev](https://relaxed-spa.deno.dev)) I try to set up an example to build an SPA with Deno that has instant deployments, too. It might be a great starting point, even though you might end up not using React.

I basically extracted the reload (in dev) and bundle mechanisms from Fresh and set up a minimal example with API backend (tRPC), React + React Router Frontend and twind for styling.

**Comment by lucacasonato** [comment]
Fresh is built to be an SSR first framework, that has islands, not an SPA framework. Maybe take a look at Aleph.js if you want an SPA framework.

**Comment by rojvv** [comment]
Or [Ultra](https://github.com/exhibitionist-digital/ultra)

**Comment by fro-profesional** [comment]
@roj1512 I saw your repo it looks good! I was planing to try to use it with https://capacitorjs.com/ to create a mobile app, do you think it might work? 🤔

**Comment by rojvv** [comment]
At this point of time, all I can say is “Good luck.”
