### ISSUE TITLE
Deno is not defined when using supabase client in island component

### ISSUE THREAD

**Issue by ieiekk** [denoland/fresh#988]
When I import [supabase js client library](https://github.com/supabase/supabase) from https://esm.sh/@supabase/supabase-js@2
in my island's button onClick handler, I got this error:

`constants.ts:198  Uncaught ReferenceError: Deno is not defined`

This error occurred since 2023.1.14, same code works before that time,
and it works fine in api route since I can get correct data response from request ( fetch data from database ).

Things I've tried:

- Run `deno cahce --reload main.ts` command
- Change supabase version
- Change deno version

**Comment by devstein** [comment]
I also just ran into this. There were no code changes in the past few weeks, but all of sudden I was seeing `Uncaught ReferenceError: Deno is not defined` when any component tried to use Supabase. 

I'm on the latest versions of Deno Fresh and using Deno Deploy.

You can see the error in the console at https://ycrm.xyz/ 

Looking at the minimized JS file the error is coming from, it appears to be from this reference to Deno

```
Deno.build.os==="linux" ? ...
```

**Comment by stephenmelnicki** [comment]
I ran in to something similar while I was working on a little toy application this week. I'll preface this with a disclaimer that I'm new to deno and fresh so I'm no expert, but I'd wager you're seeing that error because the island's code is running in the browser and `Deno` is probably not available in that context.

What worked for me was to move the supabase import and query/mutation logic out of the islands layer and into the corresponding route's handler function. Then, back in my island, I replaced that operation with an http `fetch` to that route.

If it's of any help, the toy application I mentioned is available [here on github](https://github.com/stephenmelnicki/deno_paste). The [route](https://github.com/stephenmelnicki/deno_paste/blob/main/routes/index.tsx) [handlers](https://github.com/stephenmelnicki/deno_paste/blob/main/routes/%5Bid%5D.tsx) perform the database operations while the [island](https://github.com/stephenmelnicki/deno_paste/blob/main/islands/UploadForm.tsx) makes the http requests. 

Hope that helps! 🤞

**Comment by devstein** [comment]
Hi @stephenmelnicki thanks for sharing. You are definitely right that there is island code that is running on the browser, which is why `Deno` is not available. 

I can't find any references to server-side code that would be running on the browser, but the stranger part is that the exact same code worked a few weeks ago and is now broken.

**Comment by ieiekk** [comment]
Thank you for sharing. Similar to your solutions, my final solution is to move the clientside supabase code to an independent api route.

But according to the supabase documentation, this library should be able to run on the browser, so I deduce that the problem lies in esm.sh？

**Comment by lucis** [comment]
@ieiekk try importing it from something like `https://esm.sh/@supabase/supabase-js@2.2.3?target=es2022`

**Comment by devstein** [comment]
@lucis Thank you! The `target` query parameter worked for me! Do you know why?

**Comment by lucis** [comment]
> @lucis Thank you! The `target` query parameter worked for me! Do you know why?

haha, I wish...

I don't know why it stopped working (I had used it before without `target`), but it's possibly related with changes in https://github.com/ije/esm.sh

But there's docs about this feature in https://esm.sh/

**Comment by ieiekk** [comment]
@lucis Thank you for the information! It also works on my machine.

**Comment by iuioiua** [comment]
Has anyone here been able to get Supabase running within an island? If so, are you able to provide the code?

**Comment by devstein** [comment]
> @ieiekk try importing it from something like `https://esm.sh/@supabase/supabase-js@2.2.3?target=es2022`

@iuioiua This did it for me

**Comment by iuioiua** [comment]
I did that before, but it did not work. However, I tried again now and voila! I must've done something wrong before. Thank you.
